version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(process)d - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./log/salamander.log
    encoding: utf8
    backupCount: 20
    interval: 1
    when: H

root:
  level: INFO
  handlers: [console, file]