version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    encoding: utf8
    mode: a
root:
  level: INFO
  handlers: [console, file]
