install:
  windows:
    root: "C:\\Users\\liuqiang\\Desktop\\qemu\\qemu-4.0.0"
    machine_name: "hw\\arm"
    soc_name: "hw\\arm"
    ic_name: "hw\\intc"
    bridge_name: "hw\\arm"
    timer_name: "hw\\timer"
  linux:
    root: "/root/firmware/qemu-4.0.0-rc4"
    machine_name: "hw/mips"
    ic_name: "hw/intc"
    soc_name: "hw/mips"
    bridge_name: "hw/mips"
    timer_name: "hw/timer"
  include: "include"
