install:
  windows:
    root: "C:\\Users\\liuqiang\\Desktop\\qemu\\qemu-4.0.0"
    machine_name: "hw\\arm"
    ic_name: "hw\\intc"
    soc_name: "hw\\arm"
    peripheral_name: "hw\\arm"
    timer_name: "hw\\timer"
    uart_name: "hw\\char"
  linux:
    root: "/home/liuqiang/qemu-4.0.0"
    machine_name: "hw/arm"
    ic_name: "hw/intc"
    soc_name: "hw/arm"
    peripheral_name: "hw/arm"
    timer_name: "hw/timer"
    uart_name: "hw/char"
  include: "include"
